Fix android_local_test() to include transitive resource from binary target
Summary:
Error:
ERROR: /Users/edbert/Uber/android/libraries/feature/financial-products/donation/BUILD.bazel:1:19: Building libraries/feature/financial-products/donation/test_release-class.jar (10 source files) and running annotation processors (JUnitTestProcessor) failed: (Exit 1): java failed: error executing command (from target //libraries/feature/financial-products/donation:test_release) external/remotejdk11_macos_aarch64/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
libraries/feature/financial-products/donation/src/test/java/com/uber/donation/DonationListAdapterTest.java:89: error: cannot find symbol
          ApplicationProvider.getApplicationContext(), com.uber.R.style.Theme_Helix_Light);
                                                                       ^
  symbol:   variable Theme_Helix_Light
  location: class style
libraries/feature/financial-products/donation/src/test/java/com/uber/donation/DonationListAdapterTest.java:115: error: cannot find symbol
            R.dimen.ub__donation_list_icon_width_height, R.dimen.ub__donation_list_icon_height))
                   ^
  symbol:   variable ub__donation_list_icon_width_height
  location: class dimen
libraries/feature/financial-products/donation/src/test/java/com/uber/donation/DonationListAdapterTest.java:115: error: cannot find symbol
            R.dimen.ub__donation_list_icon_width_height, R.dimen.ub__donation_list_icon_height))
                                                                ^
  symbol:   variable ub__donation_list_icon_height

Offending Diff:
https://sourcegraph.uberinternal.com/code.uber.internal/mobile/android/-/commit/008a57b8fb5a0589d1abb08e469dd84199a519e3

Source of the issue is that bazel does not compile tests the same way it does for builds. Therefore, resources are added at compile time as a transitive dependency of the src_release module. The fix is to add all the transitive resources at the end in a similar way to AndroidAPK when building a common android library.

There may be a penalty when it comes to building these tests from scratch as the cached actions and the actions we use to build the modules for the tests don't match up.

Test Plan:
USE_LOCAL_BAZEL=1 ./bazelw build --subcommands //libraries/feature/financial-products/donation:test_release --verbose_failures

{F664532713}

USE_LOCAL_BAZEL=1 ./bazelw test --subcommands //libraries/feature/financial-products/donation:test_release --verbose_failures

{F665036531}

Reviewers: oliviern

Reviewed By: oliviern

Subscribers: oliviern

Revert Plan: Git revert

Differential Revision: https://code.uberinternal.com/D8033209

[Bazel] Fix For Same Package Resources

Summary:
Original error

```

ActionInputUsageTracker: //apps/eats/features/order-tracking:src_release_kt(KotlinCompile) [6 used dep, 1205 unused dep, 8 tracked classes]
ActionInputUsageTracker: //apps/eats/features/order-tracking:src_release_kt(Javac) [241 used dep, 971 unused dep, 811 tracked classes]
[17,229 / 17,231] Building apps/eats/features/order-tracking/test_release-class.jar (63 source files) and running annotation processors (JUnitTestProcessor); 2s remote-cache, multiplex-worker
ERROR: /Users/edbert/Uber/android/apps/eats/features/order-tracking/BUILD.bazel:3:19: Building apps/eats/features/order-tracking/test_release-class.jar (63 source files) and running annotation processors (JUnitTestProcessor) failed: (Exit 1): java failed: error executing command (from target //apps/eats/features/order-tracking:test_release) external/remotejdk11_macos_aarch64/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 16 arguments skipped)
apps/eats/features/order-tracking/src/test/java/com/ubercab/eats/order_tracking/OrderTrackingInteractorTest.java:259: error: cannot find symbol
        R.string.ub__snackbar_confirm_switch_to_pickup_failure);
                ^
  symbol:   variable ub__snackbar_confirm_switch_to_pickup_failure
  location: class string

```

The reason this error occurs is because of https://sourcegraph.uberinternal.com/code.uber.internal/mobile/android/-/commit/008a57b8fb5a0589d1abb08e469dd84199a519e3 where we exclude resources from being declared as a rule output on a per-module basis. We do this as an optimization to avoid resource changes from triggering a recompilation and instead compile all the resources transitively at the end.

However, this change to the rules means that the resources_jar that is generated by the build will also not have the resources of the module in the generated resource.jar

{F709656987}

This causes a bug in testing where the test_release believes that the resource.jar that is produced from its corresponding src_release will have the resources of the src_release, not just the transitive resources. This causes the aforementioned error.

We have fixed something similar in the past with https://code.uberinternal.com/D8033209#details-tab-view but this only works on transitive dependencies. We still do not have a //module:src_release -> //module:test_release fix.

This fix will add the generated resource.jar that is a byproduct of creating the ResourceApk. ResourceApk already collects the resources transitively and adds the resources from the src_release. We can just reuse that and add it to the compilation.

Test Plan:
./bazelw test //apps/eats/features/order-tracking:src_release

{F709661009}

Reviewers: oliviern

Reviewed By: oliviern

Revert Plan: Git revert

Differential Revision: https://code.uberinternal.com/D8662211

Fix for 45315dfe76e28d9a58a8e5f65ab09814ea2a9c04