[Bazel] Transitive Resource Dependency Management
Summary:
Error:
ERROR: /Users/edbert/Uber/android/libraries/feature/financial-products/donation/BUILD.bazel:1:19: Building libraries/feature/financial-products/donation/test_release-class.jar (10 source files) and running annotation processors (JUnitTestProcessor) failed: (Exit 1): java failed: error executing command (from target //libraries/feature/financial-products/donation:test_release) external/remotejdk11_macos_aarch64/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
libraries/feature/financial-products/donation/src/test/java/com/uber/donation/DonationListAdapterTest.java:89: error: cannot find symbol
          ApplicationProvider.getApplicationContext(), com.uber.R.style.Theme_Helix_Light);
                                                                       ^
  symbol:   variable Theme_Helix_Light
  location: class style
libraries/feature/financial-products/donation/src/test/java/com/uber/donation/DonationListAdapterTest.java:115: error: cannot find symbol
            R.dimen.ub__donation_list_icon_width_height, R.dimen.ub__donation_list_icon_height))
                   ^
  symbol:   variable ub__donation_list_icon_width_height
  location: class dimen
libraries/feature/financial-products/donation/src/test/java/com/uber/donation/DonationListAdapterTest.java:115: error: cannot find symbol
            R.dimen.ub__donation_list_icon_width_height, R.dimen.ub__donation_list_icon_height))
                                                                ^
  symbol:   variable ub__donation_list_icon_height

Offending Diff:
https://sourcegraph.uberinternal.com/code.uber.internal/mobile/android/-/commit/008a57b8fb5a0589d1abb08e469dd84199a519e3

Source of the issue is that bazel does not compile tests the same way it does for builds. Therefore, resources are added at compile time as a transitive dependency of the src_release module. The fix is to add all the transitive resources at the end in a similar way to AndroidAPK when building a common android library.

There may be a penalty when it comes to building these tests from scratch as the cached actions and the actions we use to build the modules for the tests don't match up.

Test Plan:
USE_LOCAL_BAZEL=1 ./bazelw build --subcommands //libraries/feature/financial-products/donation:test_release --verbose_failures

{F664532713}

USE_LOCAL_BAZEL=1 ./bazelw test --subcommands //libraries/feature/financial-products/donation:test_release --verbose_failures

{F665036531}

Reviewers: oliviern

Reviewed By: oliviern

Subscribers: oliviern

Revert Plan: Git revert

Differential Revision: https://code.uberinternal.com/D8033209